### Get information about a Pages site
DELETE https://api.github.com/repos/afeiship/react-toast/pages
Accept: application/vnd.github.switcheroo-preview+json

{
  "source": {
    "branch": "master",
    "path": "/docs"
  }
}


### readme
GET https://api.github.com/repos/afeiship/react-toast/readme


### branches
GET https://api.github.com/repos/afeiship/ipic/branches
