
@GITHUB_API_TOKEN=GITHUB_API_TOKEN

### Get information about a Pages site
POST https://api.github.com/repos/afeiship/react-toast/pages
Accept: application/vnd.github.switcheroo-preview+json
Authorization: token {{ GITHUB_API_TOKEN }}

{
  "source": {
    "branch": "master",
    "path": "/docs"
  }
}


### readme
GET https://api.github.com/repos/afeiship/react-toast/readme


### branches
GET https://api.github.com/repos/afeiship/ipic/branches
